# Configuration for a Basic Data Pipeline
pipeline:
  name: My First Data Pipeline
  version: 1.0

# DISCLAIMER: modify the following code to match your local DuckBD instance
# postgresql:
#   host: localhost
#   port: 5432
#   username: root
#   password: root
#   database_name: chicago.db
#   options: -csearch_path=chicago_dmv,public

# Chicago Data file paths
crash_filepath: ./data/crash_data.csv
vehicle_filepath: ./data/vehicle_crash_data.csv
people_filepath: ./data/people_crash_data.csv

# PostgreSQL schema for tables
schema_PSQL: 'chicago_dmv'

# Chicago Data output tables in Postgres
crash_table_PSQL: crash
vehicle_table_PSQL: vehicle
person_table_PSQL:  person

# Chicago Data output schemas in PSQL
crash_insert_PSQL: '(crash_record_id,
                              crash_date,
                              posted_speed_limit,
                              crash_type,
                              num_units,
                              injuries_total)
                      VALUES (%s, %s, %s, %s, %s, %s)'
vehicle_insert_PSQL: '(crash_unit_id,
                              crash_record_id,
                              crash_date,
                              vehicle_id,
                              make,
                              model,
                              vehicle_year,
                              vehicle_type)
                        VALUES (%s, %s, %s, %s, %s, %s, %s, %s)'
person_insert_PSQL: '(person_id,
                              crash_record_id,
                              crash_date,
                              person_type,
                              vehicle_id,
                              sex,
                              age)
                        VALUES (%s, %s, %s, %s, %s, %s, %s)'